### ISSUE TITLE
Fix CircleGraph when >100%

### ISSUE THREAD

**Issue by sembrestels** [CommonsSwarm/tec-hatch#10]
It should be fully complete and green if >=100%.

Right now it's a bit broken:

![Screenshot from 2020-12-27 00-38-20](https://user-images.githubusercontent.com/931684/103161031-90a45c80-47dc-11eb-8b12-70dc10d00ef5.png)

**Comment by GriffGreen** [comment]
https://www.figma.com/file/D5aSEtlQ6L3dP0p0ioWpYA/TEC-Fundraising?node-id=174%3A1281

**Comment by GriffGreen** [comment]
GO TO THE "ENABLE ACCOUNT" Page

**Comment by markoprljic** [comment]
Isn't this a front-end-related issue to be fixed? In Figma I can mock up the preview but something like that already exists, I believe it's a matter of fixing the graph in the code directly. Let me know if I misunderstood something in this issue.

**Comment by GriffGreen** [comment]
we need to change it a bit more to include the 3 goals...

Min goal
Target Goal
Max Goal

![Screen Shot 2021-04-21 at 7.38.47 AM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/01d4eac6-2464-4fcf-9205-14e68e2ce57a)

**Comment by markoprljic** [comment]
![Image 2021-04-21 at 7 15 10 pm](https://user-images.githubusercontent.com/5704285/115594394-f8c00680-a2d5-11eb-8ac9-fc00794464c0.jpg)

**Comment by markoprljic** [comment]
Figma https://www.figma.com/file/A1kXJxalyebWhNmREWcTVg/TEC-HoneyPot?node-id=213%3A2560
