### ISSUE TITLE
Add custom ethereum chains to wallets (EIP-3085)

### ISSUE THREAD

**Issue by PJColombo** [CommonsSwarm/tec-hatch#52]
Add the new [Custom Network API](https://consensys.net/blog/metamask/connect-users-to-layer-2-networks-with-the-metamask-custom-networks-api) that makes the way we connect to networks on Metamask easier.

Check out this [post](https://forum.1hive.org/t/its-finally-here-the-custom-network-api/2659/4)  to learn more.

**Comment by GriffGreen** [comment]
Sundeep is taking it on!

**Comment by GriffGreen** [comment]
Sundeep, talk to @famole for getting the code :-D

**Comment by sunguru98** [comment]
Talked to @famole about it .. Working on it :) Thanks @GriffGreen

**Comment by GriffGreen** [comment]
@sunguru98 any progress?

**Comment by sunguru98** [comment]
I finally did it hahah .. Created a PR for this @GriffGreen @famole :)
