### ISSUE TITLE
Transaction failed pop-up misfire

### ISSUE THREAD

**Issue by GriffGreen** [CommonsSwarm/tec-hatch#63]
![Screen Shot 2021-04-02 at 12.43.06 PM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/4ea8dcc9-5d82-4b4e-bdef-ce5bf6cf2b3c)

**Comment by PJColombo** [comment]
This is related to the following Metamask error: 

![image](https://user-images.githubusercontent.com/33203511/113606334-28b9a980-9648-11eb-9ed8-d80e8777ca91.png)

`Block information is incomplete while ancient block sync is still in progress`. 

It might be a xDAI network problem. I'm still working on it

**Comment by GriffGreen** [comment]
Connect library calls and ETH Provider... but when you make calls to the contract... needs further discussion with @0xGabi

**Comment by GriffGreen** [comment]
We might want to stop using the OG Aragon version and start using the 1hive version to move faster and merge new changes

**Comment by GriffGreen** [comment]
@PJColombo confirm https://github.com/CommonsBuild/hatch-connector/issues/13 fixes this issue and then close

**Comment by GriffGreen** [comment]
@0xGabi

**Comment by GriffGreen** [comment]
This could be an issue with the node choice as well
