### ISSUE TITLE
Final QA on Hatch Design

### ISSUE THREAD

**Issue by GriffGreen** [CommonsSwarm/tec-hatch#88]

**Comment by sembrestels** [comment]
@markoprljic could you review that everything is in place at https://hatch-demo.netlify.app/, please?

**Comment by markoprljic** [comment]
Logo is squeezed, please replace with oroginal proportionally sized logo.

![Image 2021-05-18 at 1 11 37 pm](https://user-images.githubusercontent.com/5704285/118641683-bc9b9b00-b7da-11eb-8e62-7bb1e46a720b.jpg)

Increase the legibility of the text in the blue box, make it #ffffff
![Image 2021-05-18 at 1 12 59 pm](https://user-images.githubusercontent.com/5704285/118641754-d6d57900-b7da-11eb-9443-d16d5a83a3a1.jpg)

The rest seems good. @sembrestels
